language: python
python:
  - "2.7"
  - "3.3"

sudo: false

addons:
  apt:
    packages:
      - git
      - libtool
      - autoconf
      - automake

before_install:
  - git clone git://github.com/bitcoin/secp256k1.git libsecp256k1
  - pushd libsecp256k1
  - ./autogen.sh
  - ./configure --enable-module-recovery --enable-module-ecdh --enable-module-schnorr
  - make
  - popd
  - pip install -U setuptools cffi coverage coveralls
  - INCLUDE_DIR=$(readlink -f ./libsecp256k1/include) LIB_DIR=$(readlink -f ./libsecp256k1/.libs) pip install secp256k1

install:
  - python setup.py -q install

script:
  - LD_LIBRARY_PATH=$(readlink -f ./libsecp256k1/.libs) coverage run --source=bitjws setup.py pytest

after_success:
  - coveralls
